### ISSUE TITLE
How do I get the leaderboard to work in Slack?

### ISSUE THREAD

**Issue by nsbarr** [Donohue/karmabot#6]
I can't get this command to work for my slackbot:

```
robot.hear /// #{botname} \s+ leaderboard ///i, (msg) 
```

**Comment by Donohue** [comment]
You need to have HUBOT_SLACK_BOTNAME defined:
`heroku config:add HUBOT_SLACK_BOTNAME=karmabot`

It should work as long as that variable is defined.

**Comment by nsbarr** [comment]
word @Donohue++
